# Generated by Django 6.1.1 on 2026-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, help_text='Optional time-of-day for the due date.', null=True),
        ),
    ]
