# Generated by Django 6.1.1 on 2026-09-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='onboarding_done',
            field=models.BooleanField(default=False, help_text='True once the guided first-run tour has been completed or skipped.'),
        ),
    ]
